### ISSUE TITLE
Sync billing account id to direct project (legacy)

### ISSUE THREAD

**Issue by vikasrohit** [topcoder-platform/legacy-project-processor#13]
If v5 project has `[billingAccountId](https://github.com/topcoder-platform/tc-project-service/blob/develop/src/models/project.js#L10)` in the payload, it should be synced to the legacy project  https://github.com/topcoder-platform/legacy-project-processor/blob/develop/src/services/ProcessorService.js#L189 and https://github.com/topcoder-platform/legacy-project-processor/blob/develop/src/services/ProcessorService.js#L359.

**Comment by vikasrohit** [comment]
fyi @maxceem , we can plan it in current release.

**Comment by maxceem** [comment]
@vikasrohit I've got a clarification from one of the members who worked on this processor, this functionality looks like already implemented, does it have issues?
https://github.com/topcoder-platform/legacy-project-processor/blob/develop/src/services/ProcessorService.js#L414
https://github.com/topcoder-platform/legacy-project-processor/blob/develop/src/services/ProcessorService.js#L438-L443
https://github.com/topcoder-platform/legacy-project-processor/blob/develop/src/services/ProcessorService.js#L465-L467

**Comment by vikasrohit** [comment]
Ohk, if it is already there, we just need to verify it. I haven't verified it yet.

**Comment by maxceem** [comment]
@vikasrohit looks like this works, right?

**Comment by vikasrohit** [comment]
Verified, it is working fine. However, we might need some improvements.

1. We can avoid making query to the database if the `userId` is negative https://github.com/topcoder-platform/legacy-project-processor/blob/8f7cf1a91763771118ff0ac29cab3aff605c22b6/src/services/ProcessorService.js#L76
2. And as you said in https://github.com/topcoder-platform/legacy-project-processor/issues/12, we can avoid throwing error and instead just return null handle when either `userId` is a negative number OR we don't find the user with the given user id in the database and don't make the query https://github.com/topcoder-platform/legacy-project-processor/blob/8f7cf1a91763771118ff0ac29cab3aff605c22b6/src/services/ProcessorService.js#L97 if returned handle is null.
3. Also, we might need to allow syncing the old billing account. Right now at https://github.com/topcoder-platform/legacy-project-processor/blob/8f7cf1a91763771118ff0ac29cab3aff605c22b6/src/services/ProcessorService.js#L97 we have `where p.active = 1 and p.start_date <= current and current <= p.end_date and p.active = 1` as filter which is correct theoretically but I can see some of our API callers might be trying to associate a billing account which has ended because they might get that billing account renewed soon.

**Comment by vikasrohit** [comment]
I think 1 and 2 belongs to https://github.com/topcoder-platform/legacy-project-processor/issues/12 and 3 is not that critical for now, so lets close this issue. I am filing a new one with 3 only and moving 1 and 2 to https://github.com/topcoder-platform/legacy-project-processor/issues/12.
